env = Environment(CC='arm-none-eabi-gcc'
                  ,CXX='arm-none-eabi-g++'
                  ,LINK='arm-none-eabi-g++'
                  ,AS='arm-none-eabi-as')
env.AppendUnique(CCFLAGS=['-g', '-O0'])
env.Append(CPPDEFINES=[('STACK_SIZE', '0x1000')])
features=['usb', 'usbhid']
Export('features')
Export('env')
objs = env.SConscript('../../src/devices/atmel/samd/atsamd21e18a.SConscript')
objs += env.SConscript('../../src/SConscript')
objs += [env.Object('main.cc'), env.Object('lookup_tables.c')]
env.Program('next-usb-converter.elf', objs)
