env = Environment(CC='arm-none-eabi-gcc'
                  ,CXX='arm-none-eabi-g++'
                  ,LINK='arm-none-eabi-g++'
                  ,AS='arm-none-eabi-as')
env.AppendUnique(CCFLAGS=['-g', '-O0'])
env.Append(CPPDEFINES=[('STACK_SIZE', '0x1000')])
features=['usb', 'usbtmc', 'usbtmc488']
Export('features')
Export('env')
objs = env.SConscript('../../src/devices/renesas/ra6m1/SConstruct')
objs += env.SConscript('../../src/SConscript')
objs += [env.Object('main.cc')]
env.Program('usbtmc488.elf', objs)
